targets:
  $default:
    builders:
      mxc_router|mxc_router_gen:
        enabled: true
        generate_for:
          exclude: ['**.internal.dart']
      mxc_router|mxc_write_router_gen:
        enabled: true
        options: { 'write': true }
        generate_for:
          exclude: ['**.internal.dart']


builders:
  mxc_write_router_gen:
    target: ":mxc_write_router"
    import: "package:mxc_router/router/builder.dart"
    builder_factories: ["mxcWriteRouter"]
    build_extensions: {".route.dart": [".internal_invalid.dart"]}
    auto_apply: dependents
    build_to: source
    
  mxc_router_gen:
    target: ":mxc_router"
    import: "package:mxc_router/router/builder.dart"
    builder_factories: ["mxcRouter"]
    build_extensions: {".dart": [".internal.dart"]}
    runs_before: ['mxc_router|mxc_write_router_gen']
    auto_apply: dependents
    build_to: source